name: My Favourite Apps
favicon: null
layout_spectrum: 0.99248
typography_spectrum: 0.25125
title: My Favourite Apps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
