name: My Favourite Apps
favicon: null
layout_spectrum: 0.3252939486410469
typography_spectrum: 0.200731229968369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.01848312420770526
  lightness: 0.7116622421890497
  saturation: 0.07081342791207135
  rhythmicContrast: 0.9411105026956648
purpose: []
